# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connection.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63onnection.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x96\x01\n\x11\x43onnectionMessage\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12.\n\nstart_date\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12,\n\x08\x65nd_date\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x10\n\x08\x64istance\x18\x04 \x01(\x05\"\x85\x01\n\x0cLocationType\x12\x11\n\tperson_id\x18\x01 \x01(\x05\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x31\n\rcreation_time\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tlongitude\x18\x04 \x01(\t\x12\x10\n\x08latitude\x18\x05 \x01(\t\"U\n\nPersonType\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x14\n\x0c\x63ompany_name\x18\x03 \x01(\t\x12\n\n\x02id\x18\x04 \x01(\x05\"P\n\x10\x43onnectionResult\x12\x1f\n\x08location\x18\x01 \x01(\x0b\x32\r.LocationType\x12\x1b\n\x06person\x18\x02 \x01(\x0b\x32\x0b.PersonType\"4\n\x0e\x41llConnections\x12\"\n\x07results\x18\x01 \x03(\x0b\x32\x11.ConnectionResult2J\n\x11\x43onnectionService\x12\x35\n\x0eGetConnections\x12\x12.ConnectionMessage\x1a\x0f.AllConnectionsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'connection_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONNECTIONMESSAGE._serialized_start=54
  _CONNECTIONMESSAGE._serialized_end=204
  _LOCATIONTYPE._serialized_start=207
  _LOCATIONTYPE._serialized_end=340
  _PERSONTYPE._serialized_start=342
  _PERSONTYPE._serialized_end=427
  _CONNECTIONRESULT._serialized_start=429
  _CONNECTIONRESULT._serialized_end=509
  _ALLCONNECTIONS._serialized_start=511
  _ALLCONNECTIONS._serialized_end=563
  _CONNECTIONSERVICE._serialized_start=565
  _CONNECTIONSERVICE._serialized_end=639
# @@protoc_insertion_point(module_scope)
